# Generated by Django 6.0.5 on 2026-05-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_messageattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_members',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
