# Generated by Django 6.0.5 on 2026-05-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_max_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='expiration_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Room lifetime in hours'),
        ),
        migrations.AddField(
            model_name='room',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Room expiration time', null=True),
        ),
    ]
